### ISSUE TITLE
Unoptimized code

### ISSUE THREAD

**Issue by NoahPinel** [Aidenwjt/My-Euler-Project-Solutions#2]
01001000 01100101 01111001 00100000 01101101 01100001 01101110 00101100 00100000 01110100 01110111 01100001 01110011 00100000 01110011 01100011 01110010 01101111 01101100 01101100 01101001 01101110 01100111 00100000 01111001 01101111 01110101 01110010 00100000 01110010 01100101 01110000 01101111 00100000 01100001 01101110 01100100 00100000 01101110 01101111 01110100 01101001 01100011 01100101 01100100 00100000 01110100 01101000 01100001 01110100 00100000 01010000 00101110 00110001 00110101 00100000 01101001 01110011 00100000 01110101 01110011 01101001 01101110 01100111 00100000 01100001 00100000 01101000 01100001 01110010 01100100 00100000 01100011 01101111 01100100 01100101 01100100 00100000 01100110 01101111 01110010 01101101 01110101 01101100 01100001 00101100 00100000 01101001 01100110 00100000 01001001 00100000 01110111 01101000 01100101 01110010 01100101 00100000 01111001 01101111 01110101 00100000 01001001 00100111 01100100 00100000 01100111 01101111 01101111 01100111 01101100 01100101 00100000 01010011 01100011 01101001 01110000 01101001 00100000 01100001 01101110 01100100 00100000 01100011 01101000 01100101 01100011 01101011 00100000 01101111 01110101 01110100 00100000 01110100 01101000 01100101 01110010 01100101 00100000 01110011 01110000 01100101 01100011 01101001 01100001 01101100 00100000 01100110 01110101 01101110 01100011 01110100 01101001 01101111 01101110 01110011 00100000 01110100 01101000 01100101 01111001 00100000 01101000 01100001 01110110 01100101 00100000 01100001 00100000 01100010 01110101 01101001 01101100 01110100 00100000 01101001 01101110 00100000 01100010 01101001 01101110 01101111 01101101 01101001 01100001 01101100 00100000 01100011 01101111 01100101 01100110 01100110 01101001 01100011 01101001 01100101 01101110 01110100 00100000 01100110 01110101 01101110 01100011 01110100 01101001 01101111 01101110 00100000 01110100 01101000 01100001 01110100 00100000 01110111 01101111 01110101 01101100 01100100 00100000 01110100 01110101 01110010 01101110 00100000 01111001 01101111 01110101 01110010 00100000 01100011 01101111 01100100 01100101 00100000 01101001 01101110 01110100 01101111 00100000 01100001 00100000 01101111 01101110 01100101 00101101 01101100 01101001 01101110 01100101 01110010 00101110 00001010 01000011 01101000 01100101 01100101 01110010 01110011 00101100 00100000 01001110 01110000 01101001 01101110 01100101 01110011

**Comment by Aidenwjt** [comment]
No
